In [13]:
import numpy as np
import random

### Framework:
- $A$ sparse matrix of size $n \times m$ with each row having at most $L$ nonzero entries
- We assume that the entries in A have been scaled to [-1,1]

#### First tests: find limiting $(n,m)$ such that the computation of $A^TA$ is no longer feasible

In [14]:
def sparse_generator(m,n,L=1):
    """
    Function that generates sparse matrix with n rows and m columns, each row having at most L nonzero entries
    input:
    m: number of rows
    n: number of columns
    L: number of nonzero entries per row
    output:
    random sparse matrix A
    """
    A = np.zeros((m,n))
    for row in range(m): 
        #nonzero = random.randint(0,L)
        #new_value = [2*random.random()-1 for j in range(nonzero)] # random numbers in [-1,1]
        #index = random.sample(range(n),nonzero) # indexes of the nonzero values
        new_value = [2*random.random()-1 for j in range(L)] # random numbers in [-1,1]
        index = random.sample(range(n),L) # indexes of the nonzero values
        for (v,i) in zip(new_value, index):
            A[row,i] = v 
    return A

In [15]:
def naive_mult_np(A): # function that depends on numpy (because of dot product)
    """
    Function that computes sparse matrix multiplication
    input: 
    A: sparse matrix
    output:
    A^T A: sparse matrix product
    """
    return A.T@A

In [16]:
def naive_mult(A): # function that doesnt depend on numpy
    """
    Function that computes sparse matrix multiplication
    input: 
    A: sparse matrix
    output:
    A^T A: sparse matrix product
    """
    (m,n) = A.shape
    AProd = sum( [A[i][0]*A[i] for i in range(len(A))] )
    for r in range(1,n):
        AProd = np.vstack((AProd,sum( [A[i][r]*A[i] for i in range(len(A))] ) ))
    return AProd

In [17]:
A = sparse_generator(10,3,1)

In [18]:
naive_mult(A)

array([[0.55336282, 0.        , 0.        ],
       [0.        , 1.22526114, 0.        ],
       [0.        , 0.        , 0.65477126]])

In [19]:
naive_mult_np(A)

array([[0.55336282, 0.        , 0.        ],
       [0.        , 1.22526114, 0.        ],
       [0.        , 0.        , 0.65477126]])

In [20]:
m = 10**13
n = 10**4

In [21]:
# n = 10**2: can compute until m = 10**7
A = sparse_generator(10**2,10**8,L=1)

MemoryError: Unable to allocate 74.5 GiB for an array with shape (100, 100000000) and data type float64

In [22]:
# n = 10**2: can multiply until m = 10**4
A = sparse_generator(10**2,10**4,L=1)

naive_mult_np(A)

array([[0.09417947, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00543546]])

In [17]:
# n = 10**3: can compute until m = 10**6
A = sparse_generator(10**3,10**7,L=1)

MemoryError: Unable to allocate 74.5 GiB for an array with shape (1000, 10000000) and data type float64

In [24]:
# n = 10**3: can multiply until m = 10**4
A = sparse_generator(10**3,10**4,L=1)

naive_mult_np(A)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [25]:
# n = 10**2: can multiply until m = 10**4
A = sparse_generator(10**13,10**4,L=20)

naive_mult_np(A)

MemoryError: Unable to allocate 728. TiB for an array with shape (10000000000000, 10) and data type float64